spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always

app:
  database-path: ${DB_PATH:data/users.db}

server:
  port: ${PORT:8097}

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /api-docs

logging:
  level:
    advent.users: DEBUG
